name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Check if requirements file exists
        run: test -f requirements.txt && echo "Requirements file found" || echo "Requirements file not found"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          test -f requirements.txt && pip install -r requirements.txt || echo "Requirements file not found"
          
      - name: Run tests
        run: pytest
